#!/usr/bin/env bash

location="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PATH="${location}/git:${location}/athena:${PATH}"
export ALE_SCRIPT_BASE=$location

function atlset {
    export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
}

function atlb   { source ${location}/athena/_atlb "$@"; }
function atlenv { source ${location}/athena/_atlenv "$@"; }
function atlpkg { source ${location}/athena/_atlpkg "$@"; }
function atlref { source ${location}/athena/_atlref "$@"; }
function atlrel { source ${location}/athena/_atlrel "$@"; }
function atlrun { source ${location}/athena/_atlrun "$@"; }

function _atlas_export_environment {
    base=$(readlink -f "$1")
    src=$(readlink -f "$2")

    export ATLAS_LOCAL_ENVIRONMENT_BASE=${base}
    export ATLAS_LOCAL_ENVIRONMENT_BUILD=${base}/build
    export ATLAS_LOCAL_ENVIRONMENT_SOURCE=${src}
}

function _atlas_setup_athena {
    git atlas-init

    pushd athena && {
        git fetch upstream;
        git checkout -b devel upstream/master;
        git atlas-addpkg "$@";
        popd;
    }
}
